version: '3'

services:
  api:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6030:6030"
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    depends_on:
      - notification_db
    environment:
      UI_APP_URI: http://localhost:6050
    networks:
      default:
        aliases:
          - notification_service

  notification_db:
    image: "mongo:3.4"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 6031:27017

networks:
  default:
    external:
      name: status_page_app
