version: '3'

services:
  api:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6010:6010"
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    depends_on:
      - components_db
    networks:
      default:
        aliases:
          - components_service
  components_db:
    image: "mongo:3.4"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 6011:27017

networks:
  default:
    external:
      name: status_page_app
