version: '3'

services:
  ui-app:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 6050:6050
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    environment:
      API_GATEWAY_URI: http://api_gateway:6040
    networks:
      default:
        aliases:
          - ui_app

networks:
  default:
    external:
      name: status_page_app