version: '3'

services:
  ui-app:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 6050:6050
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    environment:
      API_GATEWAY_URI: http://localhost:6040
