version: '3'

services:
  api:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6020:6020"
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    depends_on:
      - incidents_db
    environment:
      COMPONENTS_SERVICE_URI: http://components_service:6010/components-service/api
    networks:
      default:
        aliases:
          - incidents_service
  incidents_db:
    image: "mongo:3.4"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 6021:27017

networks:
  default:
    external:
      name: status_page_app
