version: '3'

services:
  api:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "6020:6020"
    command: ["npm", "run", "dev"]
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: "mongo:3.4"
    volumes:
      - ./mongodata:/data/db
    ports:
      - 6021:27017