/**
 * @fileoverview Action types
 */

// COMPONENTS ACTIONS

export const COMPONENT_REFRESHED = 'COMPONENT_REFRESHED';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const UPDATE_COMPONENT_SORT_ORDER = 'UPDATE_COMPONENT_SORT_ORDER';
export const REFRESH_COMPONENTS = 'REFRESH_COMPONENTS';


// INCIDENTS ACTIONS
