/**
 * @fileoverview Action types
 */

// COMPONENTS ACTIONS

export const COMPONENT_REFRESHED = 'COMPONENT_REFRESHED';
export const ADD_COMPONENT = 'ADD_COMPONENT';
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT';
export const UPDATE_COMPONENT_SORT_ORDER = 'UPDATE_COMPONENT_SORT_ORDER';
export const UPDATE_COMPONENT_STATUS = 'UPDATE_COMPONENT_STATUS';
export const REFRESH_COMPONENTS = 'REFRESH_COMPONENTS';

export const ADD_COMPONENT_GROUP = 'ADD_COMPONENT_GROUP';

// INCIDENTS ACTIONS

export const ADD_INCIDENT = 'ADD_INCIDENT';
export const REMOVE_INCIDENT = 'REMOVE_INCIDENT';
