version: '3'

services:
  logger:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 6005:6005
    command: ["npm", "run", "dev"]
    env_file:
      - .env

networks:
  default:
    external:
      name: status_page_app
