#!/bin/bash

## This script provides wrapper over docker-compose commands related to this project. ##
## There is really nothing special happening than that. ##

case "$1" in
  start)
    docker-compose -f docker-compose-dev.yml up --remove-orphans
    ;;

  stop)
    docker-compose -f docker-compose-dev.yml stop
    ;;
   
  test)
    docker-compose -f test.yml run test_logger  && \
    docker stop loggerservice_test_messagingqueue_1
    ;;
   
  lint)
    docker-compose -f docker-compose-dev.yml run --rm --no-deps logger npm run lint
    ;; 
  *)
    echo $"Usage: $0 {start|stop|test|lint}"
    exit 1

esac