version: '3'

services:
  test_logger:
    image: node:8.9.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 6001:6001
    command: ["npm", "run", "test:coverage"]
    env_file:
      - test.env
    depends_on:
      - test_messagingqueue
  test_messagingqueue:
    hostname: testloggerservice
    image: rabbitmq:3.6.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_USE_LONGNAME=true
    ports:
      - 6002:5672